// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	models "github.com/evrintobing17/ecommence-REST/app/models"
	mock "github.com/stretchr/testify/mock"
)

// OrderRepository is an autogenerated mock type for the OrderRepository type
type OrderRepository struct {
	mock.Mock
}

// GetListOrder provides a mock function with given fields: id
func (_m *OrderRepository) GetListOrder(id int) (*[]models.Order, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetListOrder")
	}

	var r0 *[]models.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*[]models.Order, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *[]models.Order); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]models.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSellerListOrder provides a mock function with given fields: id
func (_m *OrderRepository) GetSellerListOrder(id int) (*[]models.Order, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetSellerListOrder")
	}

	var r0 *[]models.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*[]models.Order, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *[]models.Order); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]models.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertOrder provides a mock function with given fields: _a0
func (_m *OrderRepository) InsertOrder(_a0 *models.Order) (*models.Order, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for InsertOrder")
	}

	var r0 *models.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(*models.Order) (*models.Order, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*models.Order) *models.Order); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(*models.Order) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateOrder provides a mock function with given fields: updateData
func (_m *OrderRepository) UpdateOrder(updateData map[string]interface{}) (*models.Order, error) {
	ret := _m.Called(updateData)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrder")
	}

	var r0 *models.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(map[string]interface{}) (*models.Order, error)); ok {
		return rf(updateData)
	}
	if rf, ok := ret.Get(0).(func(map[string]interface{}) *models.Order); ok {
		r0 = rf(updateData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(map[string]interface{}) error); ok {
		r1 = rf(updateData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOrderRepository creates a new instance of OrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderRepository {
	mock := &OrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
